# Generated by Django 3.1.7 on 2021-03-30 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeptName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobResponsibilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextBoxDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=250)),
                ('writenDate', models.DateTimeField(default=None, null=True)),
                ('vivaDate', models.DateTimeField(default=None, null=True)),
                ('vivaLik', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(max_length=100)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.deptdb')),
            ],
        ),
        migrations.CreateModel(
            name='Viva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyDetailsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=50, null=True)),
                ('vacancyNum', models.IntegerField(blank=None, null=True)),
                ('EmploymentStatus', models.TextField(null=True)),
                ('EducationalRequirements', models.TextField(null=True)),
                ('AdditionalRequirements', models.TextField(null=True)),
                ('JobLocation', models.CharField(max_length=100, null=True)),
                ('salary', models.IntegerField(blank=None, null=True)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
                ('lastDate', models.DateTimeField(default=None, null=True)),
                ('JobResponsibilities', models.ManyToManyField(to='recruitment.JobResponsibilities')),
                ('vacancy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.vacancydb')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('cell', models.CharField(blank=True, max_length=20, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(blank=True, max_length=500, null=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.vacancydb')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicantID', models.IntegerField(blank=None, null=True)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('pastExperience', models.CharField(max_length=250, null=True)),
                ('salary', models.CharField(max_length=100)),
                ('university_Name', models.CharField(max_length=100)),
                ('noticePeriod', models.CharField(max_length=50)),
                ('coverLatter', models.FileField(upload_to='CoverLater/')),
                ('Cv', models.FileField(upload_to='Cv/')),
                ('invitation_sent', models.BooleanField(default=False)),
                ('written_link_sent', models.BooleanField(default=False)),
                ('viva_link_sent', models.BooleanField(default=False)),
                ('apply_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.vacancydb')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
