# Generated by Django 3.1.7 on 2021-03-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicantID', models.IntegerField(max_length=20)),
                ('name', models.CharField(max_length=25)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(default=None, max_length=20, null=True)),
                ('pastExperience', models.CharField(max_length=250, null=True)),
                ('salary', models.CharField(max_length=100)),
                ('university_Name', models.CharField(max_length=100)),
                ('noticePeriod', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('coverLatter', models.FileField(upload_to='CoverLater/')),
                ('Cv', models.FileField(upload_to='Cv/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeptDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeptId', models.IntegerField(max_length=20)),
                ('DeptName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobPositionDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobPId', models.IntegerField(max_length=20)),
                ('JobPosition', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeptID', models.IntegerField(max_length=20)),
                ('JobPID', models.IntegerField(max_length=20)),
                ('JobPositions', models.TextField(max_length=500)),
                ('startTime', models.DateTimeField(default=None, null=True)),
                ('endTime', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextBoxDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=250)),
                ('writenDate', models.DateTimeField(default=None, null=True)),
                ('vivaDate', models.DateTimeField(default=None, null=True)),
                ('vivaLik', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyDB',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('vacancy', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyDetailsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.IntegerField(max_length=20)),
                ('vacancyNum', models.IntegerField(max_length=20)),
                ('position', models.CharField(max_length=250)),
                ('shortDescription', models.TextField(max_length=500)),
                ('requirement', models.TextField(max_length=1000)),
                ('additionalInformation', models.CharField(max_length=200)),
                ('officeLocation', models.CharField(max_length=100)),
                ('lastDate', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WrittenAnsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examId', models.IntegerField(max_length=20)),
                ('definition', models.TextField(max_length=500)),
                ('theory', models.TextField(max_length=500)),
                ('idTest', models.TextField(max_length=500)),
                ('math1', models.TextField(max_length=500)),
                ('math2', models.TextField(max_length=500)),
                ('math3', models.TextField(max_length=500)),
                ('syntax1', models.TextField(max_length=500)),
                ('syntax2', models.TextField(max_length=500)),
                ('syntax3', models.TextField(max_length=500)),
                ('syntax4', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WrittenExamPagedB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qSl', models.IntegerField(max_length=20)),
                ('label1', models.CharField(max_length=100)),
                ('label2', models.TextField(max_length=500)),
                ('label3', models.TextField(max_length=500)),
                ('label4', models.TextField(max_length=500)),
                ('label5', models.TextField(max_length=500)),
                ('label6', models.TextField(max_length=500)),
                ('label7', models.TextField(max_length=500)),
                ('label8', models.TextField(max_length=500)),
                ('label9', models.TextField(max_length=500)),
                ('label10', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobPiD', models.IntegerField(max_length=20)),
                ('questionLabel', models.TextField(max_length=500)),
                ('question', models.TextField(max_length=250)),
                ('categories', models.ManyToManyField(to='recruitment.Category')),
            ],
        ),
    ]
