# Generated by Django 3.1.7 on 2021-03-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applydb',
            name='applicantID',
            field=models.IntegerField(blank=None, null=True),
        ),
        migrations.AlterField(
            model_name='deptdb',
            name='DeptId',
            field=models.IntegerField(blank=None, null=True),
        ),
        migrations.AlterField(
            model_name='jobpositiondb',
            name='JobPId',
            field=models.IntegerField(blank=None, null=True),
        ),
        migrations.AlterField(
            model_name='qdetail',
            name='DeptID',
            field=models.IntegerField(blank=None, null=True),
        ),
        migrations.AlterField(
            model_name='qdetails',
            name='JobPiD',
            field=models.IntegerField(blank=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacancydetailsdb',
            name='sl',
            field=models.IntegerField(blank=None, null=True),
        ),
        migrations.AlterField(
            model_name='writtenansdb',
            name='examId',
            field=models.IntegerField(blank=None, null=True),
        ),
        migrations.AlterField(
            model_name='writtenexampagedb',
            name='qSl',
            field=models.IntegerField(blank=None, null=True),
        ),
    ]
