# Generated by Django 3.1.7 on 2021-03-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20210315_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qdetails',
            name='categories',
            field=models.ManyToManyField(related_name='WrittenExamPagedB', to='recruitment.Category'),
        ),
    ]
