# Generated by Django 3.1.7 on 2021-03-15 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_auto_20210315_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qdetails',
            name='questionLabel',
        ),
    ]
