# Generated by Django 3.1.7 on 2021-03-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_remove_qdetails_questionlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qdetails',
            name='categories',
            field=models.ManyToManyField(to='recruitment.Category'),
        ),
    ]
