# Generated by Django 3.1.7 on 2021-03-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_auto_20210315_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancydetailsdb',
            name='additionalInformation',
        ),
        migrations.RemoveField(
            model_name='vacancydetailsdb',
            name='officeLocation',
        ),
        migrations.RemoveField(
            model_name='vacancydetailsdb',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='vacancydetailsdb',
            name='shortDescription',
        ),
        migrations.AddField(
            model_name='vacancydetailsdb',
            name='AdditionalRequirements',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vacancydetailsdb',
            name='CompanyName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vacancydetailsdb',
            name='EducationalRequirements',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vacancydetailsdb',
            name='EmploymentStatus',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vacancydetailsdb',
            name='JobLocation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacancydetailsdb',
            name='JobResponsibilities',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vacancydetailsdb',
            name='salary',
            field=models.IntegerField(blank=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacancydetailsdb',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
