# Generated by Django 3.1.7 on 2021-03-23 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_auto_20210316_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writtenansdb',
            old_name='idTest',
            new_name='iqTest',
        ),
    ]
